### ISSUE TITLE
R-1: Authentication

### ISSUE THREAD

**Issue by MacMalainey** [UofA-Blueprint/DishZero#21]
### Description:

As a user I want to be able to authenticate before I use the DishZero application's functionality

### Stories:

- [x] #26 
- [x] #27 
- [x] #28 

### Design:

*to be completed*

### User Problem:

DishZero Executives need to be able to track which users have dishes checked out, and limit access to certain parts of the app based on an authenticated user's set role

### User Outcome:

- Hypothesis:
  - With a trusted authentication system that is required to use the app, DishZero Customers will authenticate, giving executives information to be able to track dishes, and can be used to provide
- Risk:
  - Users will be turned away from the authentication system and therefore may not check out dishes when they obtain one, or will not use the DishZero service entirely

### Personas:

- Executive: Authenticate to access Admin panel, track users that have dishes currently checked out
- Volunteers: Authenticate to access dish check-in service
- Customers: Authenticate to access dish check-out service, access personal usage insights and statistics

### MVP:

Login page, limit to users with a University of Alberta CCID, Credentials kept between pages accesses, Logout page

### Acceptance Criteria:

- [ ] I need to be able to log in with credential(s) that are usable with University of Alberta's SSO only
- [ ] I need to be able to log out
- [ ] I need to be able to close the page and after 24 hours re-open the page and still be logged in
- [ ] I need to be able to log off
 - [ ] I need to be able to close the page after logging off, reopen it, and still be logged off

### Nonfunctional requirements:

- [ ] The login and logout pages need to display and function properly on a mobile screen of all sizes
- [ ] The authentication system should be available 99% of the time

### Environments:

Web

### Architecture:

TBD

### Exclusion:

None
