### ISSUE TITLE
R-1.1 Able to login

### ISSUE THREAD

**Issue by MacMalainey** [UofA-Blueprint/DishZero#26]
### Description:

As a user I want to be able able to login using my own UAlberta CCID through the Google/UAlberta SSO - so that all my actions performed on the website from there on are associated with my unique account

### Criteria:

- [ ] User should be able to authenticate
- [ ] After login the current session should remain tied to the user
- [ ] Should only be able to login if the provided credentials are for a valid University of Alberta CCID Account

### Tasks:

- [x] #63
- [x] #64 
- [x] #65
