### ISSUE TITLE
R-1.3: Able to logout

### ISSUE THREAD

**Issue by MacMalainey** [UofA-Blueprint/DishZero#28]
### Description:

As a user I should be able to logout so that my credentials are no longer tied to actions on the website in the browser I logged out of

### Criteria:

- [ ] User should be able to logout
- [ ] Actions on the website should no longer be tied to the user's account
- [ ] Website should function as if no user is logged in
- [ ] Another user should be able to login as expected

### Tasks:

- [x] #122
- [x] #123
