### ISSUE TITLE
R-2: Container Check-Out

### ISSUE THREAD

**Issue by MacMalainey** [UofA-Blueprint/DishZero#29]
### Description:

As a user I want to be able to check out containers through the DishZero website

### Stories:

TODO

### Design:

*to be completed*

### User Problem:

Customers need to be able to check out dishes that they have received from vendors when they receive them, using the information provided through the scannable QR code.

### User Outcome:

- Hypothesis:
  - Using the common and well-known QR-code technology, customers when receiving the container will scan the code and automatically check in the dish whenever they receive them
- Risk:
  - Customers if they find the check-out system to be too frustrating will bypass that step, disabling any ability to track the dishes. Or customers may stop using the service entirely.

### Personas:

- Customers: Check-out dishes

### MVP:

Scan QR code to check out container, if user is not currently logged in request that they log in before proceeding.
Logging of check-out events.

### Acceptance Criteria:

- [ ] I need to be able to check out a container by scanning the QR code from another app and navigating to the provided link
- [ ] I need to be forced to login when I check-out a dish when not logged in
- [ ] I need to only be able to check out dishes that I know the ID of (which is only accessible through their QR code)
- [ ] Dishes checked out by me must be tied to my account while I have them checked out
- [ ] If I skip authorization the check-out even should still be logged
- [ ] I need to be able to check out multiple containers at once in the website

### Nonfunctional requirements:

- [ ] The associated UI pages need to display and function properly on a mobile screen of all sizes
- [ ] The check-out system should be available 90% of the time during peak hours of 11am - 7pm MT
- [ ] During peak hours the platform should be able to handle minimum 100 simultaneous check-out transactions

### Environments:

Web

### Architecture:

TBD

### Exclusion:

None
