### ISSUE TITLE
R-3 Container Check-In

### ISSUE THREAD

**Issue by MacMalainey** [UofA-Blueprint/DishZero#30]
### Description:

As a volunteer I want to be able to check in containers through the DishZero website

### Stories:

TODO

### Design:

*to be completed*

### User Problem:

Volunteers need to be able to check in dishes that they have picked up, using the information provided through the scannable QR code.

### User Outcome:

- Hypothesis:
  - Using the volunteer portal, volunteers as part of their duty will check-in dishes leading to an efficient process that helps track DishZero's impact
- Risk:
  - Volunteers won't understand the system and will find it frustrating to use, leading to less efficient work and possible turn-over of volunteers. Volunteers may use the system incorrectly leading to incorrect results.

### Personas:

- Volunteers: Check-indishes

### MVP:

Scan QR code to check in container through volunteer portal, volunteer portal only accessible through volunteer users.
Logging of check-in events.

### Acceptance Criteria:

- [ ] I need to be able to check in a container by scanning the QR code from the volunteer portal
- [ ] I need to be logged in as a volunteer to access the volunteer portal
- [ ] I need to not be able to easily mistake the volunteer portal for the regular container check-out screen
- [ ] I need to be able to mark if the container is broken when I check it in
- [ ] Check-in events must be logged and associated with my account

### Nonfunctional requirements:

- [ ] The associated UI pages need to display and function properly on a mobile screen of all sizes
- [ ] The check-out system should be available 90% of the time

### Environments:

Web

### Architecture:

TBD

### Exclusion:

None
