### ISSUE TITLE
R-7: Customer Home Page

### ISSUE THREAD

**Issue by MacMalainey** [UofA-Blueprint/DishZero#31]
### Description:

As a user I want some general pages to provide some extra information about DishZero and specific insights about my usage of DishZero

### Stories:

TODO

### Design:

*to be completed*

### User Problem:

Users need to have a landing (home) page for the app, as well they need to be able to see their own statistics for the usage of DishZero

### User Outcome:

- Hypothesis:
  - Having customer focused landing pages will help the customer feel good about using the platform by seeing their own impact, but also through being able to access more DishZero information through the home page
- Risk:
  - Users may get confused between this and the other website, users may find it hard to navigate and drop the platform

### Personas:

- Users: uses the DishZero website
- Customers: Specific usage insights

### MVP:

General home page

### Acceptance Criteria:

- [ ] I need to be placed on the general landing page when I open the website from the root url
- [ ] I need to be able to see my statistics on my personal customer homepage

### Nonfunctional requirements:

- [ ] The associated UI pages need to display and function properly on a mobile screen of all sizes
- [ ] The home page should be available 99% of the time

### Environments:

Web

### Architecture:

TBD

### Exclusion:

None
