### ISSUE TITLE
R-2.1 Able to Check-Out Container

### ISSUE THREAD

**Issue by MacMalainey** [UofA-Blueprint/DishZero#34]
### Description:

As a user I want to be able to check out a dish that I have know the ID of

### Criteria:

- [ ] Customer should be able to check out a dish if they
  - [ ] Scan the QR Code through external application and follow the link
  - [ ] Scan the QR Code through the web app in the check-out screen
- [ ] Customer should be forced to login when attempting to check-out a dish but is unauthorized
- [ ] Customer should not be forced to login when attempting to check-out a dish and is authorized
- [ ] Checked-out dishes should be associated with the logged in user
- [ ] An unauthorized check-out should still be logged in the database

### Tasks:

- [ ] Implement UI for check-out page
- [ ] Implement login prompt for checking-out when unauthorized
- [ ] Implement logging of checked-out dishes
- [ ] Implement associating dish check-out events with the authorized user
