### ISSUE TITLE
R-3.1 Able to Check-In Containers

### ISSUE THREAD

**Issue by MacMalainey** [UofA-Blueprint/DishZero#45]
### Description:

As a volunteer I want to be able to check in a dish that I know the ID of

### Criteria:

- [ ] Volunteer should be able to check in a dish if they have access to the ID/QR code of the dish
- [ ] Volunteers should only be able to check in a dish through the volunteer portal
- [ ] A check in should not be possible from if the user is not an authorized volunteer or executive

### Tasks:

- [ ] Implement UI for check-in page
- [ ] Implement permissions check for accessing the volunteer page
- [ ] Implement permissions check for creating check-in events
