### ISSUE TITLE
R-4.2: Log Check In

### ISSUE THREAD

**Issue by Akarsh654** [UofA-Blueprint/DishZero#46]
### Description:

As an executive I want an event to be logged when a container is checked in by a volunteer

### Criteria:

- [ ] Whenever a dish is checked in the database should be updated accordingly
- [ ] Check in log must contain
  - [ ] Timestamp
  - [ ] User ID
  - [ ] Borrow (check-out event) ID
  - [ ] Condition

### Tasks:

- [x] #105 
- [x] #87 
- [ ] #83
