### ISSUE TITLE
R-3.5 Describe Condition of Container at Check-in

### ISSUE THREAD

**Issue by MacMalainey** [UofA-Blueprint/DishZero#61]
### Description:

As a volunteer I want to be able to describe the condition of the container when I check it in so that I may report whether or not any damage has been done to it

### Criteria:

- [ ] Volunteer should be able to describe the condition of the container that they just checked in

### Tasks:

- [ ] Implement description UI
- [ ] Update container condition in database
