### ISSUE TITLE
Spec: Propose implementation for tracking lost dishes

### ISSUE THREAD

**Issue by MacMalainey** [UofA-Blueprint/DishZero#74]
Currently we do not have a handler for when a dish is lost.

Our current method of tracking is "has it been checked back in?"

We need a way to mark a dish as lost in a trackable format such that:
 - The last person to check it out no longer receives notifications to return it
 - If the dish was never checked back in:
   - The last time it was checked out is known
   - The last user who checked it out is known
 - If the dish is found again (checked-out or checked-in) the lost status is overridden
 - Lost dishes can easily be reported to the admins
 
Criteria:
 - [ ] Potentially new/updated requirements
 - [ ] Proposed changes to ERD/Database Schema
 - [ ] Proposed flow charts / state diagrams for illustrating functionality
